#Application list:

App :=
# App+= MCU_RlyFristTest
# App+= MCU_LedButtonSwitch
# App+= MCU_AssemblyAndCMixing
# App+= MCU_CtoASM
# App+= MCU_FindingMax
App+= RCC_Config168Mhz
App+= RTC_Config
App+= SPI_ILI9341_ex
